In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3196, 7178, 7905, 2003],
 [3196, 7178, 7905, 1271],
 [3196, 6084, 7905, 4460],
 [3593, 383, 1872, 8191, 7215],
 [3593, 383, 1872, 8191, 1550],
 [9694, 3196, 1821, 7905, 7930],
 [3826, 3026, 8362, 8191]]

In [7]:
## word Embedding Representation
#from tensorflow.keras.processing.sequence import pad_sequences

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3196 7178 7905 2003]
 [   0    0    0    0 3196 7178 7905 1271]
 [   0    0    0    0 3196 6084 7905 4460]
 [   0    0    0 3593  383 1872 8191 7215]
 [   0    0    0 3593  383 1872 8191 1550]
 [   0    0    0 9694 3196 1821 7905 7930]
 [   0    0    0    0 3826 3026 8362 8191]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Ilya\Documents\Data science course\rnn\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 424ms/step


array([[[-0.03653958, -0.04431317,  0.03100451, -0.0160076 ,
         -0.03851717,  0.02966871, -0.04267256, -0.00115247,
         -0.0446118 ,  0.02784449],
        [-0.03653958, -0.04431317,  0.03100451, -0.0160076 ,
         -0.03851717,  0.02966871, -0.04267256, -0.00115247,
         -0.0446118 ,  0.02784449],
        [-0.03653958, -0.04431317,  0.03100451, -0.0160076 ,
         -0.03851717,  0.02966871, -0.04267256, -0.00115247,
         -0.0446118 ,  0.02784449],
        [-0.03653958, -0.04431317,  0.03100451, -0.0160076 ,
         -0.03851717,  0.02966871, -0.04267256, -0.00115247,
         -0.0446118 ,  0.02784449],
        [-0.03940803,  0.01378976, -0.028555  ,  0.04498496,
          0.03752675,  0.00255377,  0.03709911, -0.01954198,
         -0.03581884,  0.02657868],
        [-0.04749975, -0.03017042,  0.02210272, -0.03112239,
          0.01843578,  0.03958369,  0.03125421, -0.00362828,
          0.00365626, -0.0206213 ],
        [ 0.04602859,  0.01432712, -0.02578509,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3196, 7178, 7905, 2003], dtype=int32)

In [ ]:
model.predict(embedded_docs[0:1])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>